//! Machine-readable canon index (Wave C / LC-C1).
//!
//! `assets/lore/index.ron` lists every canonical lore `id`, generated by
//! walking the frontmatter of the design-repo lore tree. Game code and data
//! reference a canon entity by its `id`, never by retyping its name;
//! [`LoreIndex`] is the load-time view of that id set. The test below keeps the
//! index in sync with the lore tree (it reads the design repo from the
//! filesystem and skips when that tree is not checked out, e.g. on public CI).

use crate::assets::{Asset, AssetCache, AssetExt, BoxedError, Ron, SharedString};
use hashbrown::HashSet;
use serde::{Deserialize, Serialize};

/// The canonical set of every lore `id`, loaded from `assets/lore/index.ron`.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct LoreIndex {
    pub ids: Vec<String>,
}

impl Asset for LoreIndex {
    fn load(cache: &AssetCache, specifier: &SharedString) -> Result<Self, BoxedError> {
        Ok(cache.load::<Ron<LoreIndex>>(specifier)?.read().0.clone())
    }
}

impl LoreIndex {
    /// Load the canonical lore index (panics if the asset is
    /// missing/malformed).
    pub fn load_expect_cloned() -> Self { Self::load_expect("lore.index").cloned() }

    /// Borrowed view of the id set, for membership checks.
    pub fn set(&self) -> HashSet<&str> { self.ids.iter().map(String::as_str).collect() }

    /// Whether `id` is a known canon id.
    pub fn contains(&self, id: &str) -> bool { self.ids.iter().any(|i| i == id) }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::{
        fs,
        path::{Path, PathBuf},
    };

    /// The design-repo lore tree, relative to this crate.
    fn lore_dir() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../docs/superpowers/lore")
    }

    /// Collect every `*.md` under `dir`, recursively.
    fn md_files(dir: &Path, out: &mut Vec<PathBuf>) {
        if let Ok(entries) = fs::read_dir(dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_dir() {
                    md_files(&path, out);
                } else if path.extension().is_some_and(|e| e == "md") {
                    out.push(path);
                }
            }
        }
    }

    /// The `id:` declared in a leaf's YAML frontmatter (the first `--- ... ---`
    /// block), if any. The style-guide's template placeholder is ignored.
    fn frontmatter_id(text: &str) -> Option<String> {
        let mut lines = text.lines();
        if lines.next().map(str::trim) != Some("---") {
            return None;
        }
        for line in lines {
            if line.trim() == "---" {
                break;
            }
            if let Some(rest) = line.strip_prefix("id:") {
                let id = rest.trim().to_string();
                if id.is_empty() || id.starts_with('<') {
                    return None; // template placeholder
                }
                return Some(id);
            }
        }
        None
    }

    /// LC-C2a — every leaf's frontmatter `id` is present in `index.ron`.
    #[test]
    fn index_in_sync_with_lore_tree() {
        let dir = lore_dir();
        if !dir.exists() {
            eprintln!("SKIP index_in_sync_with_lore_tree: design lore repo not checked out");
            return;
        }
        let index = LoreIndex::load_expect_cloned();
        let known = index.set();
        let mut files = Vec::new();
        md_files(&dir, &mut files);
        let mut missing = Vec::new();
        for f in &files {
            let text = fs::read_to_string(f).unwrap_or_default();
            if let Some(id) = frontmatter_id(&text)
                && !known.contains(id.as_str())
            {
                missing.push(format!("{} ({})", id, f.display()));
            }
        }
        assert!(
            missing.is_empty(),
            "lore ids missing from assets/lore/index.ron (regenerate it):\n  {}",
            missing.join("\n  ")
        );
    }
}
