//! Machine-readable canon index + canon-lint (Wave C / LC-C1, LC-C2).
//!
//! `assets/lore/index.ron` lists every canonical lore `id`, generated by
//! walking the frontmatter of the private design-repo lore tree
//! (`docs/superpowers/lore/`). Game code and data reference a canon entity by
//! its `id`, never by retyping its name; [`LoreIndex`] is the load-time view of
//! that id set.
//!
//! The `#[cfg(test)]` canon-lint below verifies two things against the real
//! lore tree: (a) every leaf's frontmatter `id` is present in `index.ron` (the
//! index stays in sync), and (b) no denylisted D&D / Critical Role / Exandria
//! token leaks into the **in-world** prose of any leaf. Those tests read the
//! private design repo from the filesystem and **skip** when it is not checked
//! out (public CI does not have it).

use crate::assets::{Asset, AssetCache, AssetExt, BoxedError, Ron, SharedString};
use hashbrown::HashSet;
use serde::{Deserialize, Serialize};

/// The canonical set of every lore `id`, loaded from `assets/lore/index.ron`.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct LoreIndex {
    pub ids: Vec<String>,
}

impl Asset for LoreIndex {
    fn load(cache: &AssetCache, specifier: &SharedString) -> Result<Self, BoxedError> {
        Ok(cache.load::<Ron<LoreIndex>>(specifier)?.read().0.clone())
    }
}

impl LoreIndex {
    /// Load the canonical lore index (panics if the asset is
    /// missing/malformed).
    pub fn load_expect_cloned() -> Self { Self::load_expect("lore.index").cloned() }

    /// Borrowed view of the id set, for membership checks.
    pub fn set(&self) -> HashSet<&str> { self.ids.iter().map(String::as_str).collect() }

    /// Whether `id` is a known canon id.
    pub fn contains(&self, id: &str) -> bool { self.ids.iter().any(|i| i == id) }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::{
        fs,
        path::{Path, PathBuf},
    };

    /// The private design-repo lore tree, relative to this crate.
    fn lore_dir() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../docs/superpowers/lore")
    }

    /// Collect every `*.md` under `dir`, recursively.
    fn md_files(dir: &Path, out: &mut Vec<PathBuf>) {
        if let Ok(entries) = fs::read_dir(dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_dir() {
                    md_files(&path, out);
                } else if path.extension().is_some_and(|e| e == "md") {
                    out.push(path);
                }
            }
        }
    }

    /// The `id:` declared in a leaf's YAML frontmatter (the first `--- ... ---`
    /// block), if any. The style-guide's template placeholder is ignored.
    fn frontmatter_id(text: &str) -> Option<String> {
        let mut lines = text.lines();
        if lines.next().map(str::trim) != Some("---") {
            return None;
        }
        for line in lines {
            if line.trim() == "---" {
                break;
            }
            if let Some(rest) = line.strip_prefix("id:") {
                let id = rest.trim().to_string();
                if id.is_empty() || id.starts_with('<') {
                    return None; // template placeholder
                }
                return Some(id);
            }
        }
        None
    }

    /// Parse the ```denylist``` fenced block out of `70-style-guide.md`.
    fn denylist(lore: &Path) -> HashSet<String> {
        let text = fs::read_to_string(lore.join("70-style-guide.md")).unwrap_or_default();
        let mut out = HashSet::new();
        let mut inside = false;
        for line in text.lines() {
            let t = line.trim();
            if t.starts_with("```denylist") {
                inside = true;
                continue;
            }
            if inside {
                if t.starts_with("```") {
                    break;
                }
                if !t.is_empty() {
                    out.insert(t.to_lowercase());
                }
            }
        }
        out
    }

    /// Remove every complete single-line `*(...)*` out-of-world aside from
    /// `line`. (Asides hold no `)` internally, matching the authoring
    /// convention.)
    fn strip_inline_asides(line: &str) -> String {
        let mut out = String::with_capacity(line.len());
        let mut rest = line;
        while let Some(open) = rest.find("*(") {
            if let Some(close_rel) = rest[open + 2..].find(")*") {
                let close = open + 2 + close_rel;
                // keep text before the aside; the aside itself (no ')' inside) is dropped
                if rest[open + 2..close].contains(')') {
                    // a ')' inside means this isn't a clean aside; keep as-is and stop
                    out.push_str(rest);
                    return out;
                }
                out.push_str(&rest[..open]);
                rest = &rest[close + 2..];
            } else {
                break;
            }
        }
        out.push_str(rest);
        out
    }

    /// The IN-WORLD prose of a leaf, line by line (1-based line numbers), with
    /// all out-of-world zones removed: YAML frontmatter, fenced code,
    /// `*(...)*` asides (single- and multi-line), `> Provenance:` / `> ⚠️
    /// MERGED` / editorial / mapping blockquotes, and the trailing
    /// Editorial-note / IP-mapping / Notes / comparison sections. Mirrors
    /// the carve-out fixed in `70-style-guide.md §3`.
    fn in_world_lines(text: &str) -> Vec<(usize, String)> {
        const FOOTER_MARKERS: [&str; 6] = [
            "editorial note",
            "ip mapping",
            "notes & owed",
            "out-of-world",
            "### notes",
            "comparison",
        ];
        const QUOTE_MARKERS: [&str; 6] = [
            "provenance:",
            "editorial note (out-of-world)",
            "merged",
            "⚠️",
            "mapping note",
            "ip mapping",
        ];
        let lines: Vec<&str> = text.lines().collect();
        let mut out = Vec::new();
        let mut in_frontmatter = false;
        let mut frontmatter_done = false;
        let mut in_fence = false;
        let mut in_aside = false;
        let mut i = 0;
        while i < lines.len() {
            let line = lines[i];
            let trimmed = line.trim();
            let low = line.to_lowercase();
            // frontmatter
            if trimmed == "---" {
                if !frontmatter_done && !in_frontmatter {
                    in_frontmatter = true;
                    i += 1;
                    continue;
                } else if in_frontmatter {
                    in_frontmatter = false;
                    frontmatter_done = true;
                    i += 1;
                    continue;
                }
            }
            if in_frontmatter {
                i += 1;
                continue;
            }
            // fenced code
            if trimmed.starts_with("```") {
                in_fence = !in_fence;
                i += 1;
                continue;
            }
            if in_fence {
                i += 1;
                continue;
            }
            // multi-line aside continuation
            if in_aside {
                if line.contains(")*") {
                    in_aside = false;
                }
                i += 1;
                continue;
            }
            // terminal out-of-world footer section -> skip to EOF
            if trimmed.starts_with('#') && FOOTER_MARKERS.iter().any(|m| low.contains(m)) {
                break;
            }
            // out-of-world blockquote block
            if trimmed.starts_with('>') && QUOTE_MARKERS.iter().any(|m| low.contains(m)) {
                while i < lines.len() && lines[i].trim_start().starts_with('>') {
                    i += 1;
                }
                continue;
            }
            // strip complete single-line asides, then detect an opening multi-line aside
            let mut scan = strip_inline_asides(line);
            if let Some(open) = scan.find("*(")
                && !scan[open + 2..].contains(")*")
            {
                in_aside = true;
                scan.truncate(open);
            }
            out.push((i + 1, scan));
            i += 1;
        }
        out
    }

    /// Lowercased denylist tokens appearing in the IN-WORLD prose of `text`.
    /// Returns `(line_number, token)` for each hit.
    fn denylist_hits(text: &str, deny: &HashSet<String>) -> Vec<(usize, String)> {
        let mut hits = Vec::new();
        for (lineno, line) in in_world_lines(text) {
            for tok in line
                .to_lowercase()
                .split(|c: char| !(c.is_ascii_alphanumeric() || c == '\'' || c == '-'))
            {
                if !tok.is_empty() && deny.contains(tok) {
                    hits.push((lineno, tok.to_string()));
                }
            }
        }
        hits
    }

    /// LC-C2b — the canon-lint scanner is self-contained and demonstrably
    /// catches an in-world token while exempting the out-of-world zones
    /// (the "negative check").
    #[test]
    fn scanner_catches_in_world_and_exempts_out_of_world() {
        let deny: HashSet<String> = ["kord", "melora"].iter().map(|s| s.to_string()).collect();

        // in-world prose naming a denylisted god -> MUST be caught
        let bad = "---\nid: x\n---\n\nThe storm-god Kord struck the field.\n";
        assert_eq!(denylist_hits(bad, &deny), vec![(5, "kord".to_string())]);

        // the same token only in out-of-world zones -> MUST be exempt
        let ok = "---\nid: x\nref: kord\n---\n\nThe Storm-Crowned struck *(was Kord)* the \
                  field.\n\n### Editorial note (out-of-world)\nStructural slot = Kord/Melora.\n";
        assert!(
            denylist_hits(ok, &deny).is_empty(),
            "out-of-world zones must be exempt, got {:?}",
            denylist_hits(ok, &deny)
        );
    }

    /// LC-C2a — every leaf's frontmatter `id` is present in `index.ron`.
    #[test]
    fn index_in_sync_with_lore_tree() {
        let dir = lore_dir();
        if !dir.exists() {
            eprintln!("SKIP index_in_sync_with_lore_tree: private lore repo not checked out");
            return;
        }
        let index = LoreIndex::load_expect_cloned();
        let known = index.set();
        let mut files = Vec::new();
        md_files(&dir, &mut files);
        let mut missing = Vec::new();
        for f in &files {
            let text = fs::read_to_string(f).unwrap_or_default();
            if let Some(id) = frontmatter_id(&text)
                && !known.contains(id.as_str())
            {
                missing.push(format!("{} ({})", id, f.display()));
            }
        }
        assert!(
            missing.is_empty(),
            "lore ids missing from assets/lore/index.ron (regenerate it):\n  {}",
            missing.join("\n  ")
        );
    }

    /// LC-C2b — no denylisted IP token appears in the in-world prose of any
    /// leaf.
    #[test]
    fn no_denylisted_tokens_in_world() {
        let dir = lore_dir();
        if !dir.exists() {
            eprintln!("SKIP no_denylisted_tokens_in_world: private lore repo not checked out");
            return;
        }
        let deny = denylist(&dir);
        assert!(
            !deny.is_empty(),
            "denylist block not found in 70-style-guide.md"
        );
        let mut files = Vec::new();
        md_files(&dir, &mut files);
        let mut hits = Vec::new();
        for f in &files {
            // imports/ is out of scope; the style-guide itself holds the denylist
            if f.ends_with("70-style-guide.md") || f.to_string_lossy().contains("/imports/") {
                continue;
            }
            let text = fs::read_to_string(f).unwrap_or_default();
            for (lineno, tok) in denylist_hits(&text, &deny) {
                hits.push(format!("{}:{} [{}]", f.display(), lineno, tok));
            }
        }
        assert!(
            hits.is_empty(),
            "denylisted tokens in in-world prose:\n  {}",
            hits.join("\n  ")
        );
    }
}
